[build]
command = "npm install && npm run build --prefix frontend"
publish = "frontend/dist"

[functions]
directory = "frontend/netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200